apiVersion: v1
kind: Service
metadata:
  name: {{ include "nacos.fullname" . }}
  namespace: {{ include "nacos.namespace" . }}
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if and (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePorts.http }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
    - name: client
      port: {{ .Values.service.ports.client }}
      targetPort: client
      protocol: TCP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePorts.client }}
      nodePort: {{ .Values.service.nodePorts.client }}
      {{- end }}
    - name: client-rpc
      port: {{ .Values.service.ports.clientRpc }}
      targetPort: client-rpc
      protocol: TCP
    - name: raft-rpc
      port: {{ .Values.service.ports.raftRpc }}
      targetPort: raft-rpc
      protocol: TCP
    - name: mcp
      port: {{ .Values.service.ports.mcp }}
      targetPort: mcp
      protocol: TCP
  selector:
    {{- include "nacos.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nacos.headless.serviceName" . }}
  namespace: {{ include "nacos.namespace" . }}
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: client
      port: {{ .Values.service.ports.client }}
      targetPort: client
      protocol: TCP
    - name: client-rpc
      port: {{ .Values.service.ports.clientRpc }}
      targetPort: client-rpc
      protocol: TCP
    - name: raft-rpc
      port: {{ .Values.service.ports.raftRpc }}
      targetPort: raft-rpc
      protocol: TCP
    - name: old-raft
      port: 7848
      targetPort: old-raft
      protocol: TCP
    - name: mcp
      port: {{ .Values.service.ports.mcp }}
      targetPort: mcp
      protocol: TCP
  selector:
    {{- include "nacos.selectorLabels" . | nindent 4 }}
