{{/*
Copyright The Rook Authors.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and .Values.provider.kubeconfig (not .Values.provider.kubeconfigSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ceph-consumer.kubeconfigSecretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if contains "LS0t" .Values.provider.kubeconfig }}
  ## Kubeconfig is already base64 encoded
  {{ .Values.provider.kubeconfigSecretKey }}: {{ .Values.provider.kubeconfig }}
  {{- else }}
  ## Kubeconfig is plain text, encode it
  {{ .Values.provider.kubeconfigSecretKey }}: {{ .Values.provider.kubeconfig | b64enc }}
  {{- end }}
{{- end }}
