{{/*
Copyright The Rook Authors.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and .Values.provider.kubeconfig (not .Values.provider.kubeconfigSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ceph-consumer.kubeconfigSecretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- /* b64enc always produces single-line output, quote ensures valid YAML */ -}}
  {{- if hasPrefix "LS0t" .Values.provider.kubeconfig }}
  {{ .Values.provider.kubeconfigSecretKey }}: {{ .Values.provider.kubeconfig | quote }}
  {{- else }}
  {{ .Values.provider.kubeconfigSecretKey }}: {{ .Values.provider.kubeconfig | b64enc | quote }}
  {{- end }}
{{- end }}
