{{- /*
Copyright Anthropic. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.dbInit.enabled (ne .Values.database.type "sqlite") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-scripts
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: scripts
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if eq .Values.database.type "mysql" }}
  db-init.sh: |
    {{- .Files.Get "resources/scripts/db-init-mysql.sh" | nindent 4 }}
  {{- else }}
  db-init.sh: |
    {{- .Files.Get "resources/scripts/db-init-postgresql.sh" | nindent 4 }}
  {{- end }}
{{- end }}
